kotlin/src/main/resources/detekt.yml

Reasonning : 
*EmptyFunctionBlock*
Ca arrive mettons dans une implémentation NoOp. C'est quand meme gossant,  pis y'a pas de cas où j'vais laissé un body vide sans le vouloir, pis si oui ça passera pas le code review!
*Spread*
C'est juste un concern de perf, mais c'pas that bad. Selon moi si tu sais que le spread existe tu sais qu'il faut faire attention. Sinon, ca simplifie du code pareil! Genre ca c'est la facon de faire pour picocli : 
```
fun main(args: Array<String>) {
Security.insertProviderAt(BouncyCastleProvider(), 0)
PicocliRunner.run(GatewayTdCommand::class.java, *args)
}
```

Disables EmptyBlock and Spread

---

kotlin/README.md
kotlin/src/main/resources/detekt.yml

Pour `naming > PackageNaming`, je suis pas certain de la valeur par défaut `'[a-z]+(\.[a-z][A-Za-z0-9]*)*'`. Est-ce qu'on accepte le camelCase?
> Names of packages are always lower case and do not use underscores (org.example.project). Using multi-word names is generally discouraged, but if you do need to use multiple words, you can either simply concatenate them together or use the camel case (org.example.myProject).
https://kotlinlang.org/docs/reference/coding-conventions.html#naming-rules

fix(kotlin): adjust detekt rules

---

.tool-versions
kotlin/build.gradle.kts
kotlin/gradle/wrapper/gradle-wrapper.properties
kotlin/src/functionalTest/kotlin/com/equisoft/standards/kotlin/KotlinStandardsPluginFunctionalTest.kt
kotlin/src/main/kotlin/com/equisoft/standards/kotlin/KotlinStandardsPlugin.kt
kotlin/src/main/kotlin/com/equisoft/standards/kotlin/ktlint/CustomRuleSetProvider.kt
kotlin/src/main/kotlin/com/equisoft/standards/kotlin/ktlint/IndentationRule.kt
kotlin/src/main/resources/META-INF/services/com.pinterest.ktlint.core.RuleSetProvider
kotlin/src/main/resources/detekt.yml

J'ai pas eu le choix de ramener la rule de 0.36.0 pour qu'on puisse updater nos projets à 1.4 et garder le plugin en attendant qu'ils fixent l'issue. Sinon ça faisait trop de changements d'indent à faire, et certains sont assez douteux (voir https://github.com/pinterest/ktlint/issues/764)

Update to kotlin 1.4

---

javascript/packages/eslint-config-react/index.js

Considérant https://github.com/facebook/react/pull/16210, et qu'on utilise presque exclusivement des functional components. la rule est plus dans les jambes qu'autre chose

Disable react/require-default-props

---

javascript/packages/eslint-config-react/index.js
javascript/packages/eslint-config-typescript-react/index.js

Je pense que c'est assez fréquent que pour les tests on spread certaines props communes à tous les tests.

Disable react/jsx-props-no-spreading for tests

---

javascript/packages/eslint-config-react/index.js

Désolé pour le nombre de PRs, je voulais pas nécessairement tout bundler les propositions ensemble :P
Voir https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/default-props-match-prop-types.md#allowrequireddefaults

Change react/default-props-match-prop-types to allowRequiredDefaults

---

javascript/packages/eslint-config/index.js

On semble mettre l'override pas mal partout. Aussi c'est assez pratique pour du feedback juste en dev tant que c'est pas abusé.

feat(eslint): allow explicit console log levels

---

javascript/packages/eslint-config-react/package.json
javascript/packages/eslint-config-typescript-react/package.json
javascript/packages/eslint-config-typescript/index.js
javascript/packages/eslint-config-typescript/package.json
javascript/packages/eslint-config/package.json
javascript/packages/stylelint-config-styled-components/package.json
javascript/packages/stylelint-scss-config/package.json
javascript/packages/tslint-config-react/package.json
javascript/packages/tslint-config/package.json
javascript/packages/typescript-config/package.json
javascript/yarn.lock

The eslint-typescript plugin update brings https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/space-infix-ops.md which I think is a nice addition to our config.
I pre-bumped the versions to major releases and will release them when I merge. I think our configs are stable at this time.

javascript: update dependencies

---

javascript/packages/eslint-config/index.js

This is because IJ auto-format puts back imports on a single line even if max-property is reached.
This is not a nice experience and code consistency can be reached otherwise.

feat(eslint): replace max properties on imports in favor of max-len

---

javascript/packages/eslint-config-typescript/index.js

Ça me donne l'erreur 
`1:13  error  'IvariLocale' is already declared in the upper scope  no-shadow`
sinon pour
`export enum IvariLocale { Fr = 'fr', En = 'en' }`

fix(eslint-typescript) : Replace no-shadow with @typescript version

---

javascript/packages/eslint-config/index.js

C'est une proposition, mais sinon ça oblige des newlines entre les fields
```
class X {
private readonly A = 1;
private readonly B = 2;
private readonly C = 3;
}
```

chore(eslint) : Update lines-between-class-members

---

gradle/kotlin/build.gradle.kts
gradle/kotlin/src/main/resources/detekt.yml

This rule detects places where let actually improves readability.
I guess it was disabled by default for a reason.

feat(kotlin): disable UnnecessaryLet

---

javascript/packages/eslint-config/eslint.js
javascript/packages/eslint-config/package.json
javascript/yarn.lock

This makes the `--fix` flag work correctly, but we cannot filter out warnings. See https://github.com/eslint/eslint/issues/8353
Will close #136 .

fix(eslint-config): make --fix work to partially fix #136

---

gradle/build.gradle.kts
gradle/gradle/wrapper/gradle-wrapper.properties
gradle/micronaut/build.gradle.kts

micronaut-gradle-plugin:3.4.0 added support for the LAMBDA_CUSTOM runtime which I need to use.

feat(gradle/micronaut): update transitive plugins

---

renovate-config.json

Group kotlin, micronaut and equisoft minors & majors together. They will not be grouped with the larger "Gradle minors" group. Patches are not affected by this change.
This should help limit breaking changes in the "Gradle minors" group and help us merge it more often.

chore(renovate): group kotlin, micronaut, equisoft

---

.github/workflows/validate-renovate.yaml
renovate-config.json

Every time we merge a renovate PR, we must both approve it then click the merge button. Since we require approval on (almost) all PRs in branch protections, automerge will really happen only when we approve the PR.
https://docs.renovatebot.com/configuration-options/#platformautomerge

feat(renovate): enable automerge

---

javascript/packages/eslint-config-react/eslint.js
javascript/packages/eslint-config-react/package.json
javascript/packages/eslint-config-typescript-react/eslint.js
javascript/packages/eslint-config-typescript-react/package.json
javascript/packages/eslint-config-typescript/eslint.js
javascript/packages/eslint-config-typescript/package.json
javascript/yarn.lock

Ça va éviter de dépendre directement du package `eslint-config` directement même si c'est une dépendance transitive.

fix(javascript/eslint-*): include eslint script in all packages

---

gradle/openapi-sdk/build.gradle.kts
gradle/openapi-sdk/src/main/kotlin/com/equisoft/standards/gradle/openapisdk/generators/GradleSdkGenerator.kt
gradle/openapi-sdk/src/main/kotlin/com/equisoft/standards/gradle/openapisdk/generators/KotlinSdkGenerator.kt
gradle/openapi-sdk/src/main/kotlin/com/equisoft/standards/gradle/openapisdk/generators/MicronautSdkGenerator.kt
gradle/openapi-sdk/src/main/kotlin/com/equisoft/standards/gradle/openapisdk/generators/PhpSdkGenerator.kt
gradle/openapi-sdk/src/main/kotlin/com/equisoft/standards/gradle/openapisdk/generators/TypescriptSdkGenerator.kt

Fonctionne seulement pour les sdk PHP et Typescript

Enable enumUnknownDefaultCase to avoid enum breaking changes

---

renovate-config.json

I believe this would take care of unpinned transitive deps.

Enable Renovate's lock file maintenance

---

renovate-config.json

Ça va être nécessaire pour configurer les versions qui viennent des repos alpine: https://docs.renovatebot.com/modules/datasource/repology/

chore: add versioning template to Dockerfile's regexManager

---

gradle/build.gradle.kts
gradle/gradle/wrapper/gradle-wrapper.properties
gradle/kotlin/build.gradle.kts
gradle/kotlin/src/functionalTest/kotlin/com/equisoft/standards/kotlin/KotlinStandardsPluginFunctionalTest.kt
gradle/kotlin/src/main/kotlin/com/equisoft/standards/kotlin/KotlinStandardsPlugin.kt
gradle/kotlin/src/main/resources/detekt.yml
gradle/kotlin/src/test/kotlin/com/equisoft/standards/kotlin/KotlinStandardsPluginTest.kt
gradle/micronaut/src/main/kotlin/com/equisoft/standards/gradle/micronaut/MicronautPlugin.kt

kotlin 1.8.21
detekt [1.23.0](https://github.com/detekt/detekt/releases/tag/v1.23.0)
Testé dans equisoftConnect (socket) et cpanel2
BREAKING CHANGES
La tâche `lintKotlin` n'existe plus. Les vérifications de style sont toutes faites par detekt

QCTECH-554 Update kotlin and detekt + remove kotlinter

---

renovate-config.json

Allow more dependencies in the patch and (sometimes) minor groups. Some groups are only interesting for major releases.

chore(renovate): tweak groups

---

gradle/micronaut/build.gradle.kts

J'avais oublié de tester le build natif. C'est un peu gossant, mais il y a un petit problème qui est corrigé seulement dans la track v4 du plugin micronaut, qui est pas released encore. La v9 de gradle-docker-plugin marche pas avec la v3 du plugin micronaut. https://github.com/micronaut-projects/micronaut-gradle-plugin/pull/590

fix(gradle/micronaut): revert gradle-plugin update to fix build

---

javascript/packages/stylelint-config/index.js

Les règles `no-empty-first-line` et `no-missing-end-of-source-newline` sont fournies par `stylelint-stylistic` donc l'override doit être préfixé.
La règle `no-eol-whitespace` émettait beaucoup d'erreurs lorsque le code contenait une déclaration CSS avec une indentation initiale > 0.
```js
function fontSize() {
return css`
font-size: 1.5rem;
`; // <-- Erreur "Unexpected whitespace at end of line" sur cette ligne
}
```
Cependant, comme l'erreur est rapportée sur la dernière ligne du bloc, il est possible de la garder active et d'ignorer simplement les 'empty-lines'. Cette erreur est possiblement liée au même problème qui nous force à désactiver l'indentation.

fix(javascript/stylelint): Update rules for postcss-styled-syntax (QCTECH-88)

---

renovate-config.json

Ça va régler les cas comme `fix(deps): update yarn minors to v7.64.0` (il y a juste sentry qui était mis à jour) et forcer `fix(deps): update yarn minors` tout le temps.
J'ai gardé le default pour les groupes où la version fait du sens

renovate: remove `commitMessageExtra` from groups with various deps

---

.editorconfig

Source files are easier to read and edit, and a single `\n` does not impact markdown rendering.

fix(editorconfig): markdown files should use the default max_line_length

---

javascript/packages/eslint-config-typescript/index.js

ESLint doesn't deal with empty constructors that do only field initialization (ie DI). The typescript-eslint's version fixes that.

fix(eslint-config-typescript): use appropriate no-empty-function rule

---

.editorconfig

Depuis très longtemps ça me tanne que le reformat de phpstorm corresponde pas à la règle de phpcs pour les catch avec plusieurs classes.
J'ai trouvé la propriété qui force un espace autour du  `|`
Par contre, ça a le side-effect d'ajouter l'expace pour tous les types union.  Personnellement j'en met toujours un, mais je rencontre souvent du code qui en a pas.  Phpcs check pas ça.
Avant
```
try {
} catch (TypeA|TypeB $exception) {
}
private TypeA|TypeB $property;
private TypeA | TypeB $property;
```
Maintenant
```
try {
} catch (TypeA | TypeB $exception) {
}
private TypeA | TypeB $property;
```

feat(editorconfig): ij_php_spaces_around_pipe_in_union_type

---

javascript/packages/eslint-config-react/package.json
javascript/packages/eslint-config-typescript-react/package.json
javascript/packages/eslint-config-typescript/package.json
javascript/packages/eslint-config/README.md
javascript/packages/eslint-config/index.js
javascript/packages/eslint-config/package.json
javascript/yarn.lock

Requires `@stylistic/eslint-plugin` as devDependency

feat(eslint-config)!: replace indent rule by stylistic
