kronostechnologies/standards

- javascript/packages/eslint-config-typescript/index.js
See https://github.com/benmosher/eslint-plugin-import#typescript
> fix: import/no-unresolved reports false negatives on typescript

- javascript/packages/eslint-config-typescript/index.js
Woop, my bad, me manquait une virgule, pis j'avais mis des double-quotes.
> Fix eslint-typescript

- kotlin/build.gradle.kts
Je viens de publier la 0.5 avec les changes de la dernière PR.
> kotlin: prepare for next release (0.6)

- gradle/openapi-sdk/README.md
- gradle/openapi-sdk/build.gradle.kts
- gradle/openapi-sdk/src/main/kotlin/com/equisoft/standards/gradle/openapisdk/Utils.kt
- gradle/openapi-sdk/src/main/kotlin/com/equisoft/standards/gradle/openapisdk/generators/GradleSdkGenerator.kt
- gradle/openapi-sdk/src/main/kotlin/com/equisoft/standards/gradle/openapisdk/generators/MicronautSdkGenerator.kt
- gradle/openapi-sdk/src/main/kotlin/com/equisoft/standards/gradle/openapisdk/generators/PhpSdkGenerator.kt
- gradle/openapi-sdk/src/main/kotlin/com/equisoft/standards/gradle/openapisdk/generators/SdkGenerator.kt
- gradle/openapi-sdk/src/main/kotlin/com/equisoft/standards/gradle/openapisdk/generators/TypescriptSdkGenerator.kt
- gradle/openapi-sdk/src/main/kotlin/com/equisoft/standards/gradle/openapisdk/tasks/SyncRepositoryTask.kt
- gradle/openapi-sdk/src/patches/kotlin-client/libraries/jvm-okhttp/api.mustache.patch
- gradle/openapi-sdk/src/patches/kotlin-client/libraries/jvm-okhttp/infrastructure/ApiClient.kt.mustache.patch
- gradle/openapi-sdk/src/patches/kotlin-client/settings.gradle.mustache.patch
- gradle/openapi-sdk/src/patches/php/ObjectSerializer.mustache.patch
- gradle/openapi-sdk/src/patches/php/model_generic.mustache.patch
Depends on https://github.com/kronostechnologies/micronaut-project-openapi-generator/pull/2
Required by https://github.com/kronostechnologies/kronos-crm/pull/7143
Once upstream is merged and released (ideally v0.2.0), update the version here before merging.
> OpenAPI SDK: improvements and port patches from connect

- gradle/openapi-sdk/build.gradle.kts
Version 0.9.0 déjà publié avec le changement
> bump micronaut-generator

- gradle/openapi-sdk/build.gradle.kts
- gradle/openapi-sdk/src/patches/php/model_generic.mustache.patch
https://github.com/OpenAPITools/openapi-generator/issues/10244
Et ce que ça donne dans crm https://github.com/kronostechnologies/equisoft-connect-sdk-php/pull/8
> php sdk - workaround for php default enum value

- gradle/openapi-sdk/README.md
- gradle/openapi-sdk/build.gradle.kts
- gradle/openapi-sdk/src/main/kotlin/com/equisoft/standards/gradle/openapisdk/OpenApiSdkExtension.kt
- gradle/openapi-sdk/src/main/kotlin/com/equisoft/standards/gradle/openapisdk/generators/SdkGenerator.kt
- gradle/openapi-sdk/src/main/kotlin/com/equisoft/standards/gradle/openapisdk/tasks/GitTask.kt
- gradle/openapi-sdk/src/main/kotlin/com/equisoft/standards/gradle/openapisdk/tasks/PublishSdkTask.kt
- gradle/openapi-sdk/src/main/kotlin/com/equisoft/standards/gradle/openapisdk/tasks/SyncRepositoryTask.kt
Testé en local avec un PAT qui a droit sur les repos
> Allow usage of github token for openapi-sdk sync task

- gradle/openapi-sdk/build.gradle.kts
- gradle/openapi-sdk/src/main/java/org/openapitools/codegen/DefaultCodegen.java
- gradle/openapi-sdk/src/main/java/org/openapitools/codegen/languages/AbstractKotlinCodegen.java
- gradle/openapi-sdk/src/main/java/org/openapitools/codegen/languages/AbstractTypeScriptClientCodegen.java
- gradle/openapi-sdk/src/main/java/org/openapitools/codegen/languages/TypeScriptClientCodegen.java
- gradle/openapi-sdk/src/patches/kotlin-client/build.gradle.mustache.patch
> Monkey-patched openapi 5.2.1 with null type and enum default fix

- gradle/openapi-sdk/build.gradle.kts
- gradle/openapi-sdk/src/main/java/org/openapitools/codegen/languages/AbstractPhpCodegen.java
Backport second part of nullable types fix in monkey patch
https://github.com/OpenAPITools/openapi-generator/pull/10602
Voir deuxième commit pour le diff avec upstream https://github.com/kronostechnologies/standards/pull/85/commits/da332bb7cf5205e58a9c7fbe7d9254aed74bcda1
> Fix php generator nullable types

- .gitignore
- bin/gitleaks.bash
- bin/setup_asdf.bash
- gitleaks.toml
- gradle/owasp-suppressions.xml
MVP. More changes may be needed as the implementation details are improved
> feat: add gitleaks config & scripts (PI-157)

- .github/sync.yml
- .github/workflows/sync-external-resources.yml
- Makefile
- bin/gitleaks.bash
Also adds a workflow that will automatically open a PR with new gitleaks config in the actions repository.
> feat(gitleaks): allow secret scan to use a local config file

- gradle/openapi-sdk/build.gradle.kts
- gradle/openapi-sdk/src/main/java/org/openapitools/codegen/languages/AbstractPhpCodegen.java
les champs nullable sans oneOf plante
J'ai aussi updaté la pr upstream
> fix php codegen

- gradle/build.gradle.kts
- gradle/global-conventions/build.gradle.kts
- gradle/global-conventions/src/main/kotlin/com/equisoft/standards/gradle/global/GlobalConventionsPlugin.kt
- gradle/gradle/wrapper/gradle-wrapper.properties
This seems to create issues with Gradle. More investigation needed. Removing the name fixed it for me, other people don't seem to have problems afaik.
> fix(gradle/global): don't name repositories

- .github/workflows/sync-external-resources.yml
Github doesn't support team in the assignee field. Instead configure reviewers.
> ci: configure reviewers on sync PRs

- gradle/build.gradle.kts
- gradle/global-conventions/README.md
- gradle/global-conventions/src/main/kotlin/com/equisoft/standards/gradle/global/GlobalConventionsPlugin.kt
- gradle/gradle/wrapper/gradle-wrapper.properties
- gradle/kotlin/README.md
- gradle/micronaut/Makefile
- gradle/micronaut/README.md
- gradle/micronaut/build.gradle.kts
- gradle/micronaut/src/main/kotlin/com/equisoft/standards/gradle/micronaut/MicronautPlugin.kt
- gradle/micronaut/src/main/kotlin/com/equisoft/standards/gradle/micronaut/MicronautSettingsExtension.kt
- gradle/openapi-sdk/README.md
- gradle/settings.gradle.kts
Example usage : https://github.com/kronostechnologies/webapp-boilerplate/compare/fix-build?expand=1#diff-c2bcf218c14e44ade5411738da6c5e25ed00656503cf514c6ee4646d00cb6868
> feat(gradle): created plugin to wrap micronaut-gradle-plugin and allopen plugin

- gradle/micronaut/src/main/kotlin/com/equisoft/standards/gradle/micronaut/MicronautPlugin.kt
J'ai répliqué pas mal ce que le plugin micronaut-graal fait, mais pour `kapt`
> fix(gradle/micronaut): add micronaut-graal in kapt

- renovate-base.json
J'ai checké dans le code de renovate et il cherche pour https://api.github.com/ pour construire son COMPOSER_AUTH
> fix host match for composer

- gradle/build.gradle.kts
- gradle/kotlin/build.gradle.kts
- gradle/kotlin/src/functionalTest/kotlin/com/equisoft/standards/kotlin/KotlinStandardsPluginFunctionalTest.kt
Erreur qui a poppé quand j'ai voulu déployer. Probablement que j'avais pas testé avec un clean avant.
> fix(gradle/kotlin): fix tasks order

- renovate-base.json
> fix(renovate): remove github username to try to fix dependency dashboard

- renovate-base.json
J'ai ouvert une discussion dans le repo de renovate et c'est ce qu'on m'a suggéré. Ça a ben du sens en même temps!
> fix(renovate): change hostType from github to composer

- gradle/micronaut/build.gradle.kts
- gradle/micronaut/src/main/kotlin/com/equisoft/standards/gradle/micronaut/MicronautPlugin.kt
Micronaut plugin update :
- Upgrade to GraalVM 22.0.0.2 by default
> feat(gradle/micronaut): update micronaut plugin to 3.3.2 & remove aot plugin

- gradle/micronaut/src/main/kotlin/com/equisoft/standards/gradle/micronaut/MicronautPlugin.kt
J'ai mis ça ici plutôt que dans le boilerplate pour pas avoir à le répéter partout. Thoughts?
> fix(gradle/micronaut): add missing resource

- renovate-config.json
- automerge: false pour les majeur
- Groupe majeur/mineur pour docker
- Groupe majeur/mineur pour php
- docker prPriority 5 pour prioriser les update de base image
> Improve renovate config

- javascript/packages/stylelint-config/package.json
- javascript/yarn.lock
> QCTECH-1023: update stylelint peer dependency

- .github/renovate.json5
Je suis pas certain si ça va marcher, c'est un essai 🤞
> ci(renovate): fix semantic scope for lockfile PR

- Makefile
- javascript/packages/eslint-config-react/package.json
- javascript/packages/eslint-config-typescript-react/package.json
- javascript/packages/eslint-config-typescript/package.json
- javascript/packages/eslint-config/package.json
J'avais pas fait la release avec le workspace, alors les dépendances internes étaient pas sur la bonne version
> build: release eslint 3.0.5

- bin/docker-sast.sh
- bin/docker-sbom.sh
J'ai réorganisé l'ordre des params juste pour voir que les deux font pas mal la même chose. Je sais plus trop pourquoi on a encore les deux, mais je voulais pas gérer ça tout de suite.
> fix: use public ecr for trivy DB
